# Generated by Django 2.2 on 2022-07-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, unique=True)),
                ('shop', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.Shops')),
            ],
            options={
                'db_table': 'Phones',
            },
        ),
    ]
