# Generated by Django 2.2 on 2022-07-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='shop_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
